apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: toolrent-ingress
  annotations:
    # Uso el emisor de producción que configuré antes
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    # Fuerzo la redirección a HTTPS para seguridad
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  ingressClassName: nginx
  rules:
    # Defino mi dominio dinámico con nip.io basado en mi IP elástica
    - host: toolrent.54.207.116.60.nip.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80
          - path: /images
            pathType: Prefix
            backend:
              service:
                name: toolrent-service-prod
                port:
                  number: 80
          - path: /auth
            pathType: Prefix
            backend:
              service:
                name: toolrent-service-prod
                port:
                  number: 80
          - path: /user
            pathType: Prefix
            backend:
              service:
                name: toolrent-service-prod
                port:
                  number: 80
          - path: /tool
            pathType: Prefix
            backend:
              service:
                name: toolrent-service-prod
                port:
                  number: 80
          - path: /inventory
            pathType: Prefix
            backend:
              service:
                name: toolrent-service-prod
                port:
                  number: 80
          - path: /loan
            pathType: Prefix
            backend:
              service:
                name: toolrent-service-prod
                port:
                  number: 80
          - path: /loantool
            pathType: Prefix
            backend:
              service:
                name: toolrent-service-prod
                port:
                  number: 80
          - path: /kardex
            pathType: Prefix
            backend:
              service:
                name: toolrent-service-prod
                port:
                  number: 80
  tls:
    # Configuro el certificado para este dominio específico
    - hosts:
        - toolrent.54.207.116.60.nip.io
      secretName: toolrent-prod-tls