apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: toolrent-ingress
  annotations:
    cert-manager.io/cluster-issuer: "self-signed"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - toolrent.192.168.39.45.nip.io
      secretName: toolrent-local-tls
  rules:
    - host: toolrent.192.168.39.45.nip.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80
          - path: /images
            pathType: Prefix
            backend:
              service:
                name: toolrent-service
                port:
                  number: 80
          - path: /auth
            pathType: Prefix
            backend:
              service:
                name: toolrent-service
                port:
                  number: 80
          - path: /user
            pathType: Prefix
            backend:
              service:
                name: toolrent-service
                port:
                  number: 80
          - path: /tool
            pathType: Prefix
            backend:
              service:
                name: toolrent-service
                port:
                  number: 80
          - path: /api/inventory
            pathType: Prefix
            backend:
              service:
                name: toolrent-service
                port:
                  number: 80
          - path: /loan
            pathType: Prefix
            backend:
              service:
                name: toolrent-service
                port:
                  number: 80
          - path: /loantool
            pathType: Prefix
            backend:
              service:
                name: toolrent-service
                port:
                  number: 80
          - path: /kardex
            pathType: Prefix
            backend:
              service:
                name: toolrent-service
                port:
                  number: 80
