apiVersion: v1
kind: ConfigMap
metadata:
  name: global-config
data:
  POSTGRES_USER: "mharko"
  DB_PORT: "5432"

  KEYCLOAK_URL: "http://192.168.39.45:31000"
  KEYCLOAK_ISSUER_URL: "http://192.168.39.45:31000"
  KEYCLOAK_REALM: "ToolRent"
  KEYCLOAK_CLIENT_ID: "toolrent-backend"
  KEYCLOAK_CLIENT_SECRET: "WrJwjf6iuZGJX6eMfqSP5n1lfTKrV1Sk"

  BACKEND_URL: "https://toolrent.192.168.39.45.nip.io"